// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Irina_AntiAudioDelay","status":true,"description":"<AntiAudioDelay> for RPG Maker MV version 1.6.2.","parameters":{"":"","LoadAheadIndex":"10","CacheLimits":"","CacheLimitBgm":"10","CacheLimitBgs":"10","CacheLimitMe":"10","CacheLimitSe":"10"}},
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"--------------------","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"TC001_Custom_Plugin","status":true,"description":"Custom Plugins for TheCrafters001 RPG Maker MV Games.","parameters":{"Game_Title":"Keep Control - Remastered","Game_Author":"TheCrafters001"}},
{"name":"--------------------","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"MOG_Credits","status":true,"description":"(v1.1) Adiciona a cena de créditos na tela de título.","parameters":{"Command Name":"Credits","Scrolling Speed":"1"}},
{"name":"MOG_TitleSplashScreen","status":true,"description":"(v1.1 *) Adiciona logos antes da tela de título.","parameters":{"Number of Logos":"1","Slash Duration":"60","Splash Fade Duration":"2","Full Screen Mode":"false"}},
{"name":"--------------------","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"GameJolt","status":true,"description":"Use the GameJolt API in your RPG Maker MV game.","parameters":{"Game ID":"533117","Private Key":"07314403d5feada1338d57c7f72f00b2","Login on start":"false","Add button to main menu":"true","Show notifications":"true","Trophy notification text":"You got a trophy!"}},
{"name":"--------------------","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}}
];
